# By Index Label

In [2]:
import numpy as np 
import pandas as pd

In [29]:
pokemon= pd.read_csv("pokemon_full.csv")
pokemon

,#,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [32]:
pokemon=pd.read_csv("Pokemon_full.csv" , index_col=["Pokemon"] )
pokemon

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Pokemon,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,600,80,110,120,130,90,70,6,True

In [34]:
pokemon= pd.read_csv("pokemon_full.csv", index_col="Pokemon" , usecols=[ "Pokemon", "Type 1"], squeeze= True)
pokemon.head(3)

Pokemon
Bulbasaur    Grass
Ivysaur      Grass
Venusaur     Grass
Name: Type 1, dtype: object

# THE INDEX HAS NOW GOT THE LABELS OF POKEMON NAMES AND NOW CAN BE USED TO EXTRACT THE SERIES VALUE . 

# ALSO THE VALUES STILL HAVE INDEX POSITIONS ALLOCATED IN MEMORY WHICH IS THOUGH NOT VISIBLE BUT STILL USABLE

In [15]:




print(pokemon[0])
print(pokemon.index[0])
print(pokemon.values[0])
print(pokemon["Hoopa"])

Grass
Bulbasaur
Grass
Psychic

In [16]:


pokemon.sort_index(ascending=True)

Pokemon
Abomasnow      Grass
Abra         Psychic
Absol           Dark
Accelgor         Bug
Aegislash      Steel
              ...
Zoroark         Dark
Zorua           Dark
Zubat         Poison
Zweilous        Dark
Zygarde       Dragon
Name: Type, Length: 721, dtype: object

In [17]:


pokemon.sort_values(ascending=True)

Pokemon
Leavanny        Bug
Burmy           Bug
Scolipede       Bug
Genesect        Bug
Kricketune      Bug
              ...
Panpour       Water
Seel          Water
Dewgong       Water
Politoed      Water
Chinchou      Water
Name: Type, Length: 721, dtype: object

# PLAYING WITH SERIES

In [18]:

pokemon[[100,23,14,52]]

Pokemon
Electrode    Electric
Arbok          Poison
Beedrill          Bug
Persian        Normal
Name: Type, dtype: object

In [19]:
pokemon[["Politoed", "Arbok" , "Bulbasaur"]]

Pokemon
Politoed      Water
Arbok        Poison
Bulbasaur     Grass
Name: Type, dtype: object

In [26]:
pokemon[ "Bulbasaur" : "Metapod"]

Pokemon
Bulbasaur     Grass
Ivysaur       Grass
Venusaur      Grass
Charmander     Fire
Charmeleon     Fire
Charizard      Fire
Squirtle      Water
Wartortle     Water
Blastoise     Water
Caterpie        Bug
Metapod         Bug
Name: Type, dtype: object

In [20]:
## if index label doesnt exist it will return an error

In [22]:
## if one of the index label doesnt exist it will execute the code and return nan
pokemon[["Politoed", "Arbok" , "xyz"]]

Pokemon
Politoed     Water
Arbok       Poison
xyz            NaN
Name: Type, dtype: object

In [24]:
## this doesnt work as index out of bound
##pokemon[[100,21,10000]]